### ISSUE TITLE
菜单在手机浏览器看起来比较奇怪

### ISSUE THREAD

**Issue by CyrusYip** [earfanfan/yf#4]
![Screenshot_2021-04-21-10-03-32-424_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/60951091/115488698-86c3cf00-a28d-11eb-80be-dd9e83288f7f.jpg)

右边那里都挤在一起了。把菜单只留下一个语言，应该就不会挤压了吧。

**Comment by earfanfan** [comment]
@CyrusYip 好主意，回头我找时间改改。谢谢你！

**Comment by CyrusYip** [comment]
不客气，我觉得改成中文好些，因为内容都是中文。
